name: cloud
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.12.0
  firebase_analytics: ^10.6.1
  firebase_core: ^2.19.0
  firebase_messaging: ^14.7.3
  firebase_app_installations: ^0.2.5+7


 
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

