// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtZrnMx_TWhIzTMoWKBnysPnmFjX8Se9g',
    appId: '1:290094919242:web:55b192d41bfeb47c8d80b3',
    messagingSenderId: '290094919242',
    projectId: 'cloud-messaging-21fd1',
    authDomain: 'cloud-messaging-21fd1.firebaseapp.com',
    storageBucket: 'cloud-messaging-21fd1.firebasestorage.app',
    measurementId: 'G-XSPSFGWE1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUa7kvrVjVcHerSowbszquCgIc9fl1iUQ',
    appId: '1:290094919242:android:01905cbc2aa6343d8d80b3',
    messagingSenderId: '290094919242',
    projectId: 'cloud-messaging-21fd1',
    storageBucket: 'cloud-messaging-21fd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlN_xqEf3WW_tXT1bLbjOMwghn1cg9cJ8',
    appId: '1:290094919242:ios:b1070a679587d6578d80b3',
    messagingSenderId: '290094919242',
    projectId: 'cloud-messaging-21fd1',
    storageBucket: 'cloud-messaging-21fd1.firebasestorage.app',
    iosBundleId: 'com.example.cloud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlN_xqEf3WW_tXT1bLbjOMwghn1cg9cJ8',
    appId: '1:290094919242:ios:b1070a679587d6578d80b3',
    messagingSenderId: '290094919242',
    projectId: 'cloud-messaging-21fd1',
    storageBucket: 'cloud-messaging-21fd1.firebasestorage.app',
    iosBundleId: 'com.example.cloud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtZrnMx_TWhIzTMoWKBnysPnmFjX8Se9g',
    appId: '1:290094919242:web:d3471edbd58a27908d80b3',
    messagingSenderId: '290094919242',
    projectId: 'cloud-messaging-21fd1',
    authDomain: 'cloud-messaging-21fd1.firebaseapp.com',
    storageBucket: 'cloud-messaging-21fd1.firebasestorage.app',
    measurementId: 'G-TSH85N4JB6',
  );
}
